apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusterconfigs
spec:
  generators:
  - list:
      elements:
      - cluster: rosa-4c9wq
        url: https://api.rosa-4c9wq.bo87.p1.openshiftapps.com:6443
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-clusterconfigs'
    spec:
      project: default
      source:
        directory:
          jsonnet: {}
          recurse: true
        repoURL: https://github.com/navyseal8/IaaC.git
        targetRevision: HEAD
        path: applicationset/list-generator/clusterconfigs/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: clusterconfigs
