apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusterconfigs
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://1.2.3.4
      - cluster: engineering-prod
        url: https://2.4.6.8
      - cluster: finance-preprod
        url: https://9.8.7.6
  template:
    metadata:
      name: '{{cluster}}-clusterconfigs'
    spec:
      project: default
      source:
        repoURL: https://github.com/navyseal8/IaaC.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/clusterconfigs/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: clusterconfigs
